# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Manuel Jordan
author: Einsteins Erbe
email: erbe.einstein@gmail.com
description: My personal site and some of my projects
description_long: >- # this means to ignore newlines until "baseurl:"
  My personal site and some of my projects.
  Here's currently not much to see yet :(
  But I will occasionally add more content in the future.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: EinsteinsErbe1
github_username: EinsteinsErbe
linkedin_username: manuel-jordan-1350a8121
patreon_username: einsteinserbe
youtube_channel: UC7QhA4vvA82Fit-jEsPLr7w
youtube_channel_name: Einsteins Erbe
itchio_username: einsteinserbe

# Google Analytics
google_analytics: UA-132788549-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
